---
functional:
  - Регистрация нового аккаунта, включая OAuth через GitHub и Discord
  - Авторизация и выход из аккаунта
  - Форма восстановления пароля в интерфейсе входа
  - Просмотр и редактирование профиля пользователя
  - Просмотр соревнований других участников
  - Создание новой игры и подключение к существующей
  - Написание кода с возможностью просмотра кода оппонента
  - Отслеживание таймера игры
  - Просмотр рейтинга игр
  - Выбор игрового режима (по ссылке, случайный соперник, бот, турниры)
  - Настройка уровня сложности (легкий/средний/сложный)
  - Создание и управление турнирами
  - Поддержка нескольких языков программирования (Python, JS и др.)
  - Проверка работы автодополнения кода и синтаксической подсветки
  - Обработка некорректного кода
  - Корректная интерпретация и выполнение кода
  - Обмен сообщениями в чате
  - Смена языка задания
  - Переключение между светлой и темной темой
  - Минимальный набор данных при OAuth-регистрации (с fallback для email)
  - Обработка занятого email (предложение входа или восстановления)
  - Сохранение истории попыток при ошибках в коде
  - Автоматическое переключение синтаксиса при смене языка
  - Возможность репорта решения соперника
non-functional:
  - Удобный интерфейс с оптимизированной производительностью
  - Безопасное хранение пользовательских данных
  - Адаптивный дизайн для мобильных устройств
  - Совместимость с актуальными версиями браузеров
  - Масштабируемость под высокую нагрузку (1000+ пользователей)
  - Кросс-платформенная доступность
  - Индикаторы загрузки при выполнении действий
  - Подтверждение при выходе из игры
implicit:
  - Быстрая загрузка страниц (2-3 сек)
  - Гибридная обработка высокой нагрузки (очереди вместо ошибок)
  - Защита от SQL-инъекций и XSS
  - Адаптивность интерфейса (320px-4K без горизонтального скролла)
  - Сохранение сессии при навигации
  - Понятные сообщения об ошибках
  - Логирование действий
  - Отзывчивый интерфейс без лагов
  - Оптимальное время обработки задач
  - Интуитивные элементы управления
  - Уведомления о бездействии
  - Балансировка скорости интернета в PvP-режимах
  - Сбалансированная сложность задач
  - Уведомления о дисконнекте соперника
  - Корректное отображение таймеров
  - Стабильная работа при нестабильном соединении
  - Восстановление сессии при возврате
  - Понятные сообщения при ошибках сервера
  - Таймаут для бесконечных циклов (3-5 сек)
  - Real-time обновление чата
  - Ограничение спама в чате (rate limit)
  - Мгновенное обновление рейтинга
  - Восстановление текущего матча при перезагрузке
  - Временное сохранение прогресса (5-10 мин)
  - Подтверждение при сдаче
  - Фильтрация нецензурной лексики
  - Индикатор набора сообщения соперником
