---
functional:
  - Сайт должен обеспечивать возможность регистрации и авторизации
  - Пользователи сайта должны иметь возможность проводить между собой соревнования по написанию кода
  - Во время соревнований пользователи должны видеть код друг друга
  - Соревноваться можно с любым человеком либо ботом
  - Должна быть возможность выбрать уровень сложности
  - Пользователи должны иметь возможность наблюдать за другими игроками
  - В игре должен быть чат для общения зарегестрированных пользователей
  - Должна быть возможность просмотра записи завершенной игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть доступен всегда
  - Сайт должен иметь понятный интерфейс
  - Данные должны храниться в соответствии с законодательством
